# CodeRabbit Configuration
# Enables automated code reviews with Claude AI integration
# Documentation: https://docs.coderabbit.ai

# AI Provider Configuration
ai:
  provider: claude
  model: claude-sonnet-4.5-latest
  max_tokens: 8192

# Review Settings
reviews:
  enabled: true
  auto_review: true
  drafts: false
  review_status: true
  collapse_walkthrough: false
  comment_on_changes: true
  max_files_per_review: 50
  max_file_size_kb: 500

# Language and File Configuration
languages:
  - javascript
  - typescript
  - jsx
  - tsx
  - python
  - json
  - yaml
  - markdown

# File Patterns to Review
include_patterns:
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.py"
  - "**/*.json"
  - "**/*.yaml"
  - "**/*.yml"

# Exclude Patterns (dependencies, build outputs, etc.)
exclude_patterns:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".next/**"
  - "__pycache__/**"
  - "*.egg-info/**"
  - ".pytest_cache/**"
  - ".venv/**"
  - "venv/**"
  - "coverage/**"
  - ".coverage"
  - "*.pyc"
  - ".git/**"
  - ".github/**"
  - "Archive/**"
  - ".pytest_cache/**"

# Review Focus Areas
review_focus:
  - code_quality
  - security
  - performance
  - best_practices
  - error_handling

# Claude Code Integration Settings
claude:
  enabled: true
  suggestions:
    enabled: true
    real_time: true
    max_suggestions: 5

# GitHub Integration Settings
github:
  reviews:
    enabled: true
    auto_review: true
    drafts: false
    comment_on_changes: true
  webhooks:
    enabled: true
    events:
      - pull_request
      - pull_request_review
      - push

# Skip Review Conditions
skip_review:
  - "dependabot"
  - "renovate"
  - "pre-commit"

# Notification Settings
notifications:
  enabled: true
  on_review_complete: true
  on_suggestions: true

# Project Metadata
project:
  name: "ToolBoxAI Solutions"
  type: "monorepo"
  languages: ["typescript", "python"]
  repository: "GrayGhostDev/ToolboxAI-Solutions"
