# CodeRabbit Configuration for ToolBoxAI Solutions
# Optimized for test coverage improvement from 21% to 85% target

# Review settings optimized for test coverage improvement
reviews:
  profile: "assertive"  # More thorough analysis for coverage gaps
  auto_review: true
  request_changes: "auto"
  high_level_summary: true

  # Enable comprehensive analysis tools
  tools:
    pytest-cov:
      enabled: true
    security:
      enabled: true
    performance:
      enabled: true
    complexity:
      enabled: true

# Prioritize analysis of zero-coverage files (23 files identified)
path_filters:
  # HIGH PRIORITY: Zero-coverage security files
  - "apps/backend/api/auth/auth_secure.py"
  - "apps/backend/api/auth/db_auth.py"
  - "apps/backend/api/auth/password_management.py"
  - "apps/backend/core/security/audit_logger.py"
  - "apps/backend/core/security/secrets_manager.py"
  - "apps/backend/core/security/session_manager.py"
  - "apps/backend/core/security/user_manager.py"

  # MEDIUM PRIORITY: Core infrastructure
  - "apps/backend/flask_bridge.py"
  - "apps/backend/api/v1/endpoints/mobile.py"
  - "apps/backend/api/v1/endpoints/stripe_webhooks.py"
  - "apps/backend/core/app_factory.py"
  - "apps/backend/core/cache.py"
  - "apps/backend/core/performance.py"

  # LOW COVERAGE: Core business logic
  - "core/agents/**"
  - "core/sparc/**"
  - "core/mcp/**"
  - "database/**"

# Focus reviews on test coverage improvement
path_instructions:
  - path: "apps/backend/api/auth/**"
    instructions: |
      CRITICAL: These files have 0% test coverage and handle authentication.

      Analysis Focus:
      1. Identify security vulnerabilities that need test coverage
      2. Suggest unit test cases for authentication flows
      3. Recommend integration tests for auth endpoints
      4. Highlight edge cases and error conditions needing tests
      5. Identify dependencies that need mocking

      Priority: Generate specific test cases that can be implemented immediately.

  - path: "apps/backend/core/security/**"
    instructions: |
      SECURITY CRITICAL: Zero coverage on security infrastructure.

      Analysis Focus:
      1. Audit logging test requirements
      2. Session management test scenarios
      3. User management boundary testing
      4. Secret management security tests
      5. Rate limiting and access control tests

      Output: Actionable test cases with security validation.

  - path: "core/agents/**"
    instructions: |
      BUSINESS LOGIC: Agent system needs comprehensive testing.

      Analysis Focus:
      1. Agent lifecycle testing strategies
      2. Orchestration and coordination test scenarios
      3. Mock patterns for external LLM dependencies
      4. Integration testing for multi-agent workflows
      5. Error handling and retry logic testing

      Goal: Increase coverage from current 14-56% to target levels.

  - path: "tests/**"
    instructions: |
      TEST QUALITY: Review existing tests for improvement opportunities.

      Analysis Focus:
      1. Test completeness and coverage gaps
      2. Mock usage and dependency injection
      3. Async testing patterns and best practices
      4. Test organization and maintainability
      5. Performance and reliability improvements

      Target: Optimize existing tests to increase effective coverage.

# Focus on testability and maintainability
language: "en-US"
tone_instructions: |
  Provide actionable testing recommendations with specific focus on:

  1. **Immediate Impact**: Prioritize suggestions that quickly increase coverage
  2. **Security First**: Emphasize testing for authentication and security modules
  3. **Specific Test Cases**: Provide concrete examples of test scenarios
  4. **Mock Strategies**: Suggest appropriate mocking for external dependencies
  5. **Coverage Metrics**: Relate suggestions to coverage percentage improvement

  Format responses as:
  - Priority level (HIGH/MEDIUM/LOW)
  - Estimated coverage impact
  - Specific test implementation suggestions
  - Required mocking or setup

  Target: Move from 21% to 85% coverage systematically.

# Enable advanced analysis features
early_access: true
knowledge_base:
  opt_out: false
  learnings: true

# Chat integration for interactive analysis
chat:
  auto_reply: true