FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY apps/dashboard/package*.json ./
RUN npm ci

# Copy application code
COPY apps/dashboard .

# Expose port
EXPOSE 5179

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5179"]