# GitHub Environment Configuration: Production
# This file documents the required environment variables and secrets for the production environment

name: production
description: "Production environment serving live users"

# Environment Protection Rules
protection_rules:
  wait_timer: 300  # 5 minute wait time for production deployments
  prevent_self_review: true
  required_reviewers:
    - "ToolboxAI-Solutions/maintainers"
    - "ToolboxAI-Solutions/security-team"
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false

# Environment Variables (non-sensitive)
variables:
  # Application Configuration
  APP_ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "WARNING"
  
  # API Configuration
  FASTAPI_HOST: "0.0.0.0"
  FASTAPI_PORT: "8008"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "8009"
  
  # Database Configuration (High Availability)
  DATABASE_HOST: "prod-db-cluster.toolboxai.internal"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "toolboxai_production"
  DATABASE_USER: "toolboxai_prod"
  DATABASE_READ_REPLICA_HOST: "prod-db-read.toolboxai.internal"
  
  # Redis Configuration (Cluster)
  REDIS_HOST: "prod-redis-cluster.toolboxai.internal"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CLUSTER_MODE: "true"
  
  # CORS Configuration
  CORS_ORIGINS: '["https://toolboxai.example.com", "https://app.toolboxai.example.com", "https://api.toolboxai.example.com"]'
  
  # Feature Flags
  ENABLE_DEBUG_ENDPOINTS: "false"
  ENABLE_MOCK_DATA: "false"
  ENABLE_TEST_USERS: "false"
  ENABLE_ANALYTICS: "true"
  ENABLE_MONITORING: "true"
  ENABLE_PERFORMANCE_TRACKING: "true"
  
  # AI Configuration (Production Optimized)
  AI_MODEL_TEMPERATURE: "0.3"
  MAX_TOKENS: "8000"
  AI_REQUEST_TIMEOUT: "120"
  AI_MAX_RETRIES: "3"
  
  # Rate Limiting (Production)
  RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
  RATE_LIMIT_BURST_LIMIT: "200"
  RATE_LIMIT_REDIS_ENABLED: "true"
  
  # Performance (Production Scale)
  GUNICORN_WORKERS: "8"
  GUNICORN_THREADS: "4"
  GUNICORN_TIMEOUT: "120"
  GUNICORN_KEEPALIVE: "5"
  
  # Security
  SECURITY_HEADERS_ENABLED: "true"
  HTTPS_ONLY: "true"
  SECURE_COOKIES: "true"
  
  # Monitoring
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # CDN and Static Assets
  CDN_ENABLED: "true"
  STATIC_URL_PREFIX: "https://cdn.toolboxai.example.com"
  
  # Backup and Recovery
  AUTOMATED_BACKUPS: "true"
  BACKUP_ENCRYPTION: "true"

# Required Secrets (Production Grade)
secrets:
  # Database (High Security)
  - name: DATABASE_PASSWORD
    description: "Production database master password"
    required: true
    
  - name: DATABASE_READ_REPLICA_PASSWORD
    description: "Production read replica database password"
    required: true
    
  # AI Services (Production Keys)
  - name: OPENAI_API_KEY
    description: "OpenAI API key for production (high-tier)"
    required: true
    
  - name: ANTHROPIC_API_KEY
    description: "Anthropic API key for production"
    required: true
    
  # Authentication & Security
  - name: JWT_SECRET_KEY
    description: "JWT signing secret for production (256-bit)"
    required: true
    
  - name: ENCRYPTION_KEY
    description: "AES-256 encryption key for production"
    required: true
    
  - name: SESSION_SECRET_KEY
    description: "Session encryption secret"
    required: true
    
  # External Services
  - name: REDIS_PASSWORD
    description: "Redis cluster authentication password"
    required: true
    
  # LMS Integration (Production)
  - name: SCHOOLOGY_API_KEY
    description: "Schoology production API key"
    required: true
    
  - name: SCHOOLOGY_API_SECRET
    description: "Schoology production API secret"
    required: true
    
  - name: CANVAS_API_KEY
    description: "Canvas production API key"
    required: true
    
  - name: CANVAS_API_SECRET
    description: "Canvas production API secret"
    required: true
    
  # Email Services (Production)
  - name: SMTP_PASSWORD
    description: "Production SMTP service password"
    required: true
    
  - name: SMTP_HOST
    description: "Production SMTP service host"
    required: true
    
  - name: SENDGRID_API_KEY
    description: "SendGrid API key for production email"
    required: true
    
  # Security & Compliance
  - name: SECRET_MANAGER_KEY
    description: "AWS/Azure Secret Manager access key"
    required: true
    
  - name: VAULT_TOKEN
    description: "HashiCorp Vault authentication token"
    required: false
    
  # Monitoring & Analytics
  - name: SENTRY_DSN
    description: "Sentry DSN for production error tracking"
    required: true
    
  - name: DATADOG_API_KEY
    description: "Datadog API key for monitoring"
    required: true
    
  - name: NEW_RELIC_LICENSE_KEY
    description: "New Relic license key for APM"
    required: false
    
  # CDN and Storage
  - name: AWS_ACCESS_KEY_ID
    description: "AWS access key for S3 and CloudFront"
    required: true
    
  - name: AWS_SECRET_ACCESS_KEY
    description: "AWS secret key for S3 and CloudFront"
    required: true
    
  # Payment Processing (if applicable)
  - name: STRIPE_SECRET_KEY
    description: "Stripe secret key for payment processing"
    required: false
    
  - name: STRIPE_WEBHOOK_SECRET
    description: "Stripe webhook endpoint secret"
    required: false
    
  # Third-party Integrations
  - name: GOOGLE_CLOUD_API_KEY
    description: "Google Cloud API key"
    required: false
    
  - name: MICROSOFT_GRAPH_API_KEY
    description: "Microsoft Graph API key"
    required: false

# Deployment URLs
deployment_urls:
  primary: "https://toolboxai.example.com"
  api: "https://api.toolboxai.example.com"
  dashboard: "https://app.toolboxai.example.com"
  docs: "https://docs.toolboxai.example.com"
  admin: "https://admin.toolboxai.example.com"
  cdn: "https://cdn.toolboxai.example.com"
  status: "https://status.toolboxai.example.com"

# Health Check Endpoints (Comprehensive)
health_checks:
  - name: "API Health"
    url: "https://api.toolboxai.example.com/health"
    expected_status: 200
    timeout: 10
    interval: 30
    
  - name: "Database Primary"
    url: "https://api.toolboxai.example.com/health/database"
    expected_status: 200
    timeout: 5
    interval: 60
    
  - name: "Database Read Replica"
    url: "https://api.toolboxai.example.com/health/database/readonly"
    expected_status: 200
    timeout: 5
    interval: 60
    
  - name: "Redis Cluster"
    url: "https://api.toolboxai.example.com/health/redis"
    expected_status: 200
    timeout: 5
    interval: 30
    
  - name: "AI Services"
    url: "https://api.toolboxai.example.com/health/ai"
    expected_status: 200
    timeout: 30
    interval: 300
    
  - name: "External Integrations"
    url: "https://api.toolboxai.example.com/health/integrations"
    expected_status: 200
    timeout: 30
    interval: 300
    
  - name: "CDN Health"
    url: "https://cdn.toolboxai.example.com/health.json"
    expected_status: 200
    timeout: 10
    interval: 60

# Load Testing Configuration
load_testing:
  enable: true
  target_rps: 200
  duration: "10m"
  ramp_up: "2m"
  endpoints:
    - "/health"
    - "/api/v1/user/profile"
    - "/api/v1/generate_content"
    - "/api/v1/lms/courses"
  
# Performance Monitoring
performance:
  response_time_threshold_ms: 500
  error_rate_threshold_percent: 0.1
  availability_threshold_percent: 99.9
  apdex_threshold: 0.95

# Monitoring and Logging (Production Grade)
monitoring:
  enable_debug_logging: false
  log_retention_days: 90
  enable_performance_metrics: true
  enable_error_tracking: true
  enable_uptime_monitoring: true
  enable_security_monitoring: true
  enable_compliance_logging: true
  
  # Alert Thresholds
  alert_on_error_rate: 1.0  # 1% error rate
  alert_on_response_time: 1000  # 1 second
  alert_on_cpu_usage: 80  # 80% CPU usage
  alert_on_memory_usage: 85  # 85% memory usage
  alert_on_disk_usage: 90  # 90% disk usage

# Backup Configuration (Production)
backup:
  database_backup_frequency: "hourly"
  database_backup_retention: "90 days"
  database_point_in_time_recovery: true
  
  file_backup_frequency: "daily"
  file_backup_retention: "90 days"
  
  application_backup_frequency: "daily"
  application_backup_retention: "30 days"
  
  cross_region_backup: true
  backup_encryption: true
  backup_verification: true

# Disaster Recovery
disaster_recovery:
  enable_multi_region: true
  failover_regions: ["us-west-2", "eu-west-1"]
  rto_target: "4 hours"  # Recovery Time Objective
  rpo_target: "1 hour"   # Recovery Point Objective
  automated_failover: false  # Manual approval required

# Security Configuration
security:
  enable_waf: true
  enable_ddos_protection: true
  enable_ssl_monitoring: true
  ssl_certificate_auto_renewal: true
  security_scan_frequency: "weekly"
  vulnerability_scan_frequency: "daily"
  
# Compliance
compliance:
  gdpr_enabled: true
  coppa_enabled: true
  ferpa_enabled: true
  audit_logging: true
  data_retention_policy: "7 years"
  user_data_export: true
  user_data_deletion: true