from typing import Any, Callable, Dict, Iterable, Mapping

class SettingsConfigDict(Mapping[str, Any]): ...

class BaseSettings:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def my_field(*args: Any, **kwargs: Any) -> Any: ...
def field_validator(*fields: Iterable[str], mode: str = ...) -> Callable[..., Any]: ...

"""Pydantic v2 settings compatibility stubs."""

__all__ = ["BaseSettings", "SettingsConfigDict", "my_field", "field_validator"]
