#!/bin/bash

# install_hooks.sh - Install Git hooks for ToolboxAI Roblox Environment
# This script installs the custom Git hooks for automated quality checks and project management

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$SCRIPT_DIR/..")"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
GITHUB_HOOKS_DIR="$SCRIPT_DIR/hooks"

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if we're in a Git repository
check_git_repo() {
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        log_error "This script must be run from within a Git repository"
        exit 1
    fi
    
    log_info "Git repository detected: $REPO_ROOT"
}

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."
    
    local missing_deps=()
    
    # Check Python
    if ! command -v python3 &> /dev/null; then
        missing_deps+=("python3")
    else
        local python_version=$(python3 --version | cut -d' ' -f2)
        log_info "Python version: $python_version"
    fi
    
    # Check required Python packages
    local python_packages=("requests" "pydantic" "pathlib")
    for package in "${python_packages[@]}"; do
        if ! python3 -c "import $package" 2>/dev/null; then
            missing_deps+=("python3-$package")
        fi
    done
    
    # Check Node.js (optional but recommended)
    if command -v node &> /dev/null; then
        local node_version=$(node --version)
        log_info "Node.js version: $node_version"
    else
        log_warning "Node.js not found (recommended for Dashboard development)"
    fi
    
    # Check Docker (optional)
    if command -v docker &> /dev/null; then
        local docker_version=$(docker --version | cut -d' ' -f3 | tr -d ',')
        log_info "Docker version: $docker_version"
    else
        log_warning "Docker not found (required for containerized development)"
    fi
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        log_error "Missing dependencies: ${missing_deps[*]}"
        log_info "Please install the missing dependencies and try again"
        exit 1
    fi
    
    log_success "All required dependencies found"
}

# Create hook wrapper
create_hook_wrapper() {
    local hook_name=$1
    local python_script=$2
    local hook_file="$HOOKS_DIR/$hook_name"
    
    log_info "Creating $hook_name hook..."
    
    cat > "$hook_file" << EOF
#!/bin/bash
# $hook_name hook for ToolboxAI Roblox Environment
# Auto-generated by install_hooks.sh

set -e

# Hook configuration
HOOK_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="\$(git rev-parse --show-toplevel)"
PYTHON_SCRIPT="\$REPO_ROOT/github/hooks/$python_script"

# Check if Python script exists
if [ ! -f "\$PYTHON_SCRIPT" ]; then
    echo "Error: Hook script not found: \$PYTHON_SCRIPT"
    exit 1
fi

# Set environment variables
export PYTHONPATH="\$REPO_ROOT:\$PYTHONPATH"

# Run the Python hook script
python3 "\$PYTHON_SCRIPT" "\$@"
EOF

    chmod +x "$hook_file"
    log_success "Created $hook_name hook"
}

# Install pre-commit hook
install_pre_commit_hook() {
    create_hook_wrapper "pre-commit" "pre_commit.py"
    
    # Create configuration file if it doesn't exist
    local config_file="$REPO_ROOT/.github/hooks.config.json"
    if [ ! -f "$config_file" ]; then
        log_info "Creating hooks configuration file..."
        cat > "$config_file" << EOF
{
  "pre_commit": {
    "enabled": true,
    "auto_fix": false,
    "skip_tests": false,
    "max_file_size_mb": 50,
    "python_version": "3.11",
    "security_scan_enabled": true,
    "documentation_required": false,
    "roblox_lint_enabled": true
  },
  "post_merge": {
    "enabled": true,
    "auto_install_deps": false,
    "auto_migrate_db": false,
    "send_notifications": false
  },
  "pre_push": {
    "enabled": true,
    "security_scan_enabled": true,
    "min_test_coverage": 80,
    "max_file_size_mb": 100
  }
}
EOF
        log_success "Created hooks configuration file"
    fi
}

# Install post-merge hook
install_post_merge_hook() {
    create_hook_wrapper "post-merge" "post_merge.py"
}

# Install pre-push hook
install_pre_push_hook() {
    create_hook_wrapper "pre-push" "pre_push.py"
}

# Install prepare-commit-msg hook for educational commit templates
install_prepare_commit_msg_hook() {
    local hook_file="$HOOKS_DIR/prepare-commit-msg"
    
    log_info "Creating prepare-commit-msg hook..."
    
    cat > "$hook_file" << 'EOF'
#!/bin/bash
# prepare-commit-msg hook for ToolboxAI Roblox Environment
# Provides commit message templates for educational platform development

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Only add template for regular commits (not merges, amends, etc.)
if [ -z "$COMMIT_SOURCE" ]; then
    # Check if it's an empty commit message
    if [ ! -s "$COMMIT_MSG_FILE" ]; then
        # Add educational commit template
        cat >> "$COMMIT_MSG_FILE" << 'TEMPLATE'
# ToolboxAI Educational Platform Commit Template
#
# Format: <type>(<scope>): <description>
#
# Types:
#   feat:     New educational feature (curriculum, assessment, etc.)
#   fix:      Bug fix affecting learning experience
#   edu:      Educational content improvements
#   roblox:   Roblox platform specific changes
#   api:      API/backend changes
#   agents:   AI agent system changes
#   ui:       User interface improvements
#   docs:     Documentation updates
#   test:     Test additions or modifications
#   chore:    Maintenance tasks
#
# Scopes (examples):
#   curriculum, quiz, student, teacher, roblox, agents, api, dashboard
#
# Example commits:
#   feat(curriculum): add interactive math lessons for grade 5
#   fix(roblox): resolve terrain generation issue in science labs
#   edu(assessment): improve quiz feedback for better learning outcomes
#   agents(content): enhance educational content generation accuracy
#
# Educational Impact:
# - How does this change improve the learning experience?
# - Which educational standards does this support?
# - What grade levels or subjects are affected?
#
TEMPLATE
    fi
fi
EOF

    chmod +x "$hook_file"
    log_success "Created prepare-commit-msg hook with educational templates"
}

# Install commit-msg hook for validation
install_commit_msg_hook() {
    local hook_file="$HOOKS_DIR/commit-msg"
    
    log_info "Creating commit-msg hook..."
    
    cat > "$hook_file" << 'EOF'
#!/bin/bash
# commit-msg hook for ToolboxAI Roblox Environment
# Validates commit message format for educational platform

COMMIT_MSG_FILE=$1

# Read the commit message
commit_message=$(cat "$COMMIT_MSG_FILE")

# Remove comments and empty lines
clean_message=$(echo "$commit_message" | grep -v '^#' | grep -v '^$' | head -n1)

# Skip validation for merge commits
if [[ $clean_message =~ ^Merge ]]; then
    exit 0
fi

# Check if message is empty
if [ -z "$clean_message" ]; then
    echo "Error: Empty commit message"
    exit 1
fi

# Validate format (relaxed for educational platform)
if [[ ! $clean_message =~ ^(feat|fix|edu|roblox|api|agents|ui|docs|test|chore)(\(.+\))?: .+ ]]; then
    echo "Warning: Commit message doesn't follow conventional format"
    echo "Recommended format: <type>(<scope>): <description>"
    echo "Types: feat, fix, edu, roblox, api, agents, ui, docs, test, chore"
    echo ""
    echo "Your message: $clean_message"
    echo ""
    echo "Proceeding anyway... (consider using conventional commits for better tracking)"
fi

# Check message length
if [ ${#clean_message} -gt 100 ]; then
    echo "Warning: Commit message is quite long (${#clean_message} chars)"
    echo "Consider keeping the first line under 72 characters"
fi

exit 0
EOF

    chmod +x "$hook_file"
    log_success "Created commit-msg validation hook"
}

# Setup development environment
setup_dev_environment() {
    log_info "Setting up development environment..."
    
    # Create .github directory structure
    mkdir -p "$REPO_ROOT/.github/"{workflows,sprints,metrics,sprint-reports}
    
    # Create development configuration
    local dev_config="$REPO_ROOT/.github/development.config.json"
    if [ ! -f "$dev_config" ]; then
        cat > "$dev_config" << EOF
{
  "project": "ToolboxAI Roblox Educational Environment",
  "educational_focus": true,
  "components": {
    "roblox": {
      "language": "Lua",
      "platform": "Roblox Studio",
      "focus": "Educational game development"
    },
    "api": {
      "language": "Python",
      "framework": "FastAPI",
      "focus": "Educational content API"
    },
    "agents": {
      "language": "Python",
      "framework": "LangChain/LangGraph",
      "focus": "AI-powered educational content generation"
    },
    "dashboard": {
      "language": "TypeScript",
      "framework": "React",
      "focus": "Teacher and student interfaces"
    }
  },
  "educational_standards": [
    "Common Core",
    "NGSS",
    "State Standards",
    "Custom Curriculum"
  ],
  "grade_levels": ["K-5", "6-8", "9-12", "Higher Ed"],
  "subjects": [
    "Mathematics",
    "Science",
    "History",
    "Language Arts",
    "Computer Science",
    "Art"
  ]
}
EOF
        log_success "Created development configuration"
    fi
    
    # Create CODEOWNERS file for educational platform
    local codeowners="$REPO_ROOT/.github/CODEOWNERS"
    if [ ! -f "$codeowners" ]; then
        cat > "$codeowners" << EOF
# CODEOWNERS for ToolboxAI Roblox Educational Environment
# https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

# Global owners
* @maintainers

# Educational content and curriculum
/curriculum/ @education-team
/assessments/ @education-team
README.md @education-team @maintainers

# Roblox game development
/Roblox/ @game-dev-team @education-team
*.lua @game-dev-team

# AI agents and content generation
/agents/ @ai-team
/mcp/ @ai-team
/sparc/ @ai-team
/swarm/ @ai-team

# API and backend
/server/ @backend-team
/API/GhostBackend/ @backend-team

# Frontend dashboard
/API/Dashboard/ @frontend-team

# DevOps and GitHub integration
/github/ @devops-team
/.github/ @devops-team
/docker/ @devops-team

# Documentation
/docs/ @docs-team @education-team
*.md @docs-team

# Configuration
*.json @maintainers
*.yaml @devops-team
*.yml @devops-team

# Tests
/tests/ @qa-team @backend-team @game-dev-team
EOF
        log_success "Created CODEOWNERS file"
    fi
}

# Create educational issue templates
create_issue_templates() {
    log_info "Creating educational issue templates..."
    
    local templates_dir="$REPO_ROOT/.github/ISSUE_TEMPLATE"
    mkdir -p "$templates_dir"
    
    # Bug report template
    cat > "$templates_dir/bug_report.yml" << 'EOF'
name: 🐛 Bug Report
description: Report a bug in the ToolboxAI Educational Platform
title: '[BUG] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve the ToolboxAI Educational Platform! 
        Please provide details about the bug you encountered.

  - type: dropdown
    id: component
    attributes:
      label: Platform Component
      description: Which part of the platform is affected?
      options:
        - Roblox Game Environment
        - Web Dashboard
        - API Backend
        - AI Agent System
        - LMS Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: subject
    attributes:
      label: Educational Subject
      description: If applicable, which subject area is affected?
      options:
        - Mathematics
        - Science
        - History/Social Studies
        - Language Arts
        - Computer Science
        - Art/Design
        - Multiple Subjects
        - Not Subject-Specific
    validations:
      required: false

  - type: input
    id: grade_level
    attributes:
      label: Grade Level
      description: Which grade level(s) are affected?
      placeholder: e.g., K-5, 6-8, 9-12, Higher Ed
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Educational Impact
      description: How does this bug affect the learning or teaching experience?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide relevant environment information
      placeholder: |
        - OS: [e.g. Windows, macOS, Linux]
        - Browser: [e.g. Chrome, Firefox] (if applicable)
        - Roblox Client Version: (if applicable)
        - Python Version: (if applicable)
    validations:
      required: false
EOF

    # Feature request template
    cat > "$templates_dir/feature_request.yml" << 'EOF'
name: ✨ Feature Request
description: Suggest a new educational feature
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Help us improve education through technology! 
        Describe your idea for a new educational feature.

  - type: dropdown
    id: subject
    attributes:
      label: Educational Subject
      description: Which subject area would this feature support?
      options:
        - Mathematics
        - Science
        - History/Social Studies
        - Language Arts
        - Computer Science
        - Art/Design
        - Multiple Subjects
        - Platform-Wide Feature
    validations:
      required: true

  - type: input
    id: grade_level
    attributes:
      label: Target Grade Level
      description: Which grade level(s) would benefit?
      placeholder: e.g., K-5, 6-8, 9-12, Higher Ed
    validations:
      required: true

  - type: textarea
    id: learning_objective
    attributes:
      label: Learning Objectives
      description: What educational goals would this feature support?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Educational Use Case
      description: How would teachers and students use this feature?
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Platform Components
      description: Which components would this feature involve?
      options:
        - label: Roblox Game Environment
        - label: Web Dashboard
        - label: LMS Integration
        - label: AI Content Generation
        - label: Assessment System
        - label: Student Analytics
        - label: Teacher Tools

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How would we measure the success of this feature?
      placeholder: |
        - Student engagement improvement
        - Learning outcome metrics
        - Teacher adoption rate
        - Time-to-understanding reduction
EOF

    # Educational content issue template
    cat > "$templates_dir/educational_content.yml" << 'EOF'
name: 📚 Educational Content Issue
description: Report issues with educational content or curriculum
title: '[EDU] '
labels: ['curriculum', 'education']
body:
  - type: dropdown
    id: subject
    attributes:
      label: Subject Area
      options:
        - Mathematics
        - Science
        - History/Social Studies
        - Language Arts
        - Computer Science
        - Art/Design
    validations:
      required: true

  - type: input
    id: grade_level
    attributes:
      label: Grade Level
      placeholder: e.g., 5th Grade, High School Biology
    validations:
      required: true

  - type: input
    id: standards
    attributes:
      label: Educational Standards
      description: Which standards does this relate to?
      placeholder: e.g., Common Core Math 5.NBT.1, NGSS MS-ETS1-1

  - type: textarea
    id: issue_description
    attributes:
      label: Content Issue Description
      description: Describe the educational content or pedagogical issue
    validations:
      required: true

  - type: textarea
    id: learning_impact
    attributes:
      label: Impact on Learning
      description: How does this issue affect student learning outcomes?
    validations:
      required: true

  - type: textarea
    id: teacher_perspective
    attributes:
      label: Teacher Challenges
      description: What challenges does this create for educators?

  - type: textarea
    id: suggested_improvements
    attributes:
      label: Suggested Improvements
      description: What changes would improve the educational value?
EOF

    log_success "Created educational issue templates"
}

# Test hooks installation
test_hooks() {
    log_info "Testing hooks installation..."
    
    # Test pre-commit hook
    if [ -x "$HOOKS_DIR/pre-commit" ]; then
        log_success "Pre-commit hook installed and executable"
    else
        log_error "Pre-commit hook not properly installed"
        return 1
    fi
    
    # Test post-merge hook
    if [ -x "$HOOKS_DIR/post-merge" ]; then
        log_success "Post-merge hook installed and executable"
    else
        log_error "Post-merge hook not properly installed"
        return 1
    fi
    
    # Test pre-push hook
    if [ -x "$HOOKS_DIR/pre-push" ]; then
        log_success "Pre-push hook installed and executable"
    else
        log_error "Pre-push hook not properly installed"
        return 1
    fi
    
    # Test Python scripts
    local python_scripts=("pre_commit.py" "post_merge.py" "pre_push.py")
    for script in "${python_scripts[@]}"; do
        if python3 -m py_compile "$GITHUB_HOOKS_DIR/$script"; then
            log_success "Python script $script compiles successfully"
        else
            log_error "Python script $script has compilation errors"
            return 1
        fi
    done
    
    log_success "All hooks tested successfully"
    return 0
}

# Show usage instructions
show_usage_instructions() {
    log_info "Git hooks installation completed!"
    echo
    echo -e "${GREEN}Usage Instructions:${NC}"
    echo "1. The hooks will now run automatically on git operations:"
    echo "   - pre-commit: Runs code quality checks before each commit"
    echo "   - post-merge: Runs maintenance tasks after merges"  
    echo "   - pre-push: Runs security and quality checks before pushing"
    echo
    echo -e "${GREEN}Educational Platform Features:${NC}"
    echo "- Commit templates for educational development"
    echo "- Roblox Lua syntax checking"
    echo "- Educational content validation" 
    echo "- LMS integration testing"
    echo "- AI agent code review"
    echo
    echo -e "${GREEN}Configuration:${NC}"
    echo "- Edit .github/hooks.config.json to customize hook behavior"
    echo "- Use 'git commit --no-verify' to bypass hooks temporarily"
    echo "- Use 'git push --no-verify' to bypass pre-push hooks"
    echo
    echo -e "${GREEN}Getting Help:${NC}"
    echo "- Run hooks with --help flag for detailed usage"
    echo "- Check .github/ISSUE_TEMPLATE/ for reporting issues"
    echo "- See CONTRIBUTING.md for development guidelines"
    echo
    echo -e "${BLUE}Happy coding for education! 🎓${NC}"
}

# Main installation function
main() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}  ToolboxAI Educational Platform${NC}"
    echo -e "${BLUE}  Git Hooks Installation${NC}" 
    echo -e "${BLUE}========================================${NC}"
    echo
    
    # Parse command line arguments
    local FORCE_INSTALL=false
    local SKIP_TESTS=false
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            -f|--force)
                FORCE_INSTALL=true
                shift
                ;;
            --skip-tests)
                SKIP_TESTS=true
                shift
                ;;
            -h|--help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -f, --force      Force installation even if hooks exist"
                echo "  --skip-tests     Skip testing hooks after installation"
                echo "  -h, --help       Show this help message"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
    
    # Run installation steps
    check_git_repo
    check_dependencies
    
    # Check if hooks already exist
    if [ -f "$HOOKS_DIR/pre-commit" ] && [ "$FORCE_INSTALL" = false ]; then
        log_warning "Git hooks already exist. Use --force to reinstall."
        read -p "Continue with installation? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Installation cancelled by user"
            exit 0
        fi
    fi
    
    # Create hooks directory if it doesn't exist
    mkdir -p "$HOOKS_DIR"
    
    # Install hooks
    install_pre_commit_hook
    install_post_merge_hook  
    install_pre_push_hook
    install_prepare_commit_msg_hook
    install_commit_msg_hook
    
    # Setup development environment
    setup_dev_environment
    create_issue_templates
    
    # Test installation
    if [ "$SKIP_TESTS" = false ]; then
        if ! test_hooks; then
            log_error "Hook testing failed. Please check the installation."
            exit 1
        fi
    fi
    
    # Show usage instructions
    show_usage_instructions
    
    log_success "Git hooks installation completed successfully!"
    exit 0
}

# Run main function with all arguments
main "$@"