from typing import Any, Callable

# Minimal stubs used to satisfy pyright for pydantic Field and validators

def Field(*args: Any, **kwargs: Any) -> Any: ...
def field_validator(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...

class BaseModel: ...
class BaseSettings(BaseModel): ...
